- cloudflare_worker/src/lib.rs
- cloudflare_worker/worker/worker.js
- fastly_compute/src/main.rs
- sxg_rs/src/lib.rs
So that the domain of the req url will also be checked.
> Match entire url rather than pathname for cert and validity

- README.md
- cloudflare_worker/README.md
- fastly_compute/README.md
Includes descriptions of subdirectories and general install/post-install
instructions. Also added platform-specific instructions for overriding SXG
expiration.
> Add top-level README with high-level overview.

- README.md
- cloudflare_worker/README.md
- cloudflare_worker/wrangler.example.toml
- credentials/README.md
- credentials/parse_private_key.go
- fastly_compute/README.md
Also, improve error message with parse_private_key.go parses a file with the
wrong format or key type.
> Clarify install docs.

- sxg_rs/src/headers.rs
Check alternative control headers from Cloudflare and Fastly, and additionally
disallow no-store and max-age=0 in all cases.
Fixes #8. Fixes #9.
> Disallow more cache directives.

- sxg_rs/src/headers.rs
> Remove connection headers before signing.

- cloudflare_worker/src/lib.rs
- sxg_rs/src/signature/js_signer.rs
- sxg_rs/src/signature/mod.rs
> Specify which format the JsSigner returns

- cloudflare_worker/worker/src/index.ts
This addresses the log message:
Your worker called response.clone(), but did not read the body of both
clones. This is wasteful, as it forces the system to buffer the entire
response body in memory, rather than streaming it through. This may cause
your worker to be unexpectedly terminated for going over the memory limit. If
you only meant to copy the response headers and metadata (e.g. in order to be
able to modify them), use `new Response(response.body, response)` instead.
> Cancel whichever body is unused from the tee.

- sxg_rs/src/headers.rs
- sxg_rs/src/http_parser/mod.rs
`Vary: Cookie` is not a perfect signal for whether the response varies by cookie, but it doesn't seem too have too many false-positives to make it unusable, and it's a helpful defense in depth.
> Don't sign if response varies by Cookie.

- Cargo.lock
- sxg_rs/Cargo.toml
- sxg_rs/src/signature/rust_signer.rs
- Update `p256` to `0.9.0`.
Fix unit tests in #66.
> Update p256 to 0.9.0

- Cargo.lock
- config_generator/Cargo.toml
- config_generator/src/main.rs
> Update wrangler to 1.19.3

- sxg_rs/src/headers.rs
- sxg_rs/src/link.rs
> Only emit preloads with matching allowed-alt-sxgs.

- .github/workflows/code-style.yml
- cloudflare_worker/worker/.eslintignore
- cloudflare_worker/worker/.eslintrc.json
- cloudflare_worker/worker/.prettierrc.js
- cloudflare_worker/worker/karma.conf.js
- cloudflare_worker/worker/package-lock.json
- cloudflare_worker/worker/package.json
- cloudflare_worker/worker/src/bindings.d.ts
- cloudflare_worker/worker/src/index.ts
- cloudflare_worker/worker/src/signer.ts
- cloudflare_worker/worker/src/streams.test.ts
- cloudflare_worker/worker/src/streams.ts
- cloudflare_worker/worker/src/utils.test.ts
- cloudflare_worker/worker/src/utils.ts
- cloudflare_worker/worker/src/wasmFunctions.ts
- playground/.eslintignore
- playground/.eslintrc.json
- playground/.prettierrc.js
- playground/package-lock.json
- playground/package.json
- playground/src/client/index.ts
- playground/src/index.ts
- playground/src/server/credentials.ts
- playground/src/server/fetcher.ts
- playground/src/server/index.ts
- playground/src/server/signer.ts
- playground/src/server/wasmFunctions.ts
* Use [gts](https://github.com/google/gts) to lint TypeScript files.
* Format existing files.
* Add PR checks to enforce code style.
> Add TypeScript linter

- Cargo.lock
- sxg_rs/Cargo.toml
- tools/Cargo.toml
> Update der-parser and x509-parser

- cloudflare_worker/worker/package-lock.json
Closes https://github.com/google/sxg-rs/security/dependabot/6.
> Update minimist to 1.2.6

- README.md
Added in e1f4e304.
Addresses #141.
> Document the data-sxg-no-header attribute

- sxg_rs/src/headers.rs
The follows the suggestion in #191.
> Make helper methods in Headers struct public

- sxg_rs/src/config.rs
- sxg_rs/src/lib.rs
This also follows some suggestions in #191.
> Add new constructors to create SxgWorker from parsed data

- sxg_rs/src/process_html.rs
* Update `content-length` header to the correct value after `process_html` rewrites HTML body.
* No longer adds an empty string `Link` header when no sub-resources exist.
* Fix #225
> Update content-length header when processing html

- sxg_rs/src/acme/client.rs
- sxg_rs/src/acme/mod.rs
For every ACME request, the client need to include a `AuthMethod`, which is either a JSON public key or an account ID.
Previously, `Client::post_as_get` and `Client::post_with_payload` method need `auth_method` parameter to be specified every time.
Since the `auth_method` does not often change, this PR moves `auth_method` as a member variable of `Client`, so that `Client::post_as_get` and `Client::post_with_payload` will take one less parameter.
> Set auth method as a field in ACME client

- cloudflare_worker/worker/src/index.ts
- sxg_rs/src/acme/state_machine.rs
- sxg_rs/src/lib.rs
- sxg_rs/src/wasm_worker.rs
- tools/src/commands/apply_acme_cert.rs
- typescript_utilities/src/wasmFunctions.ts
* Keep multiple certificate PEM strings in ACME storage.
* Renew ACME certificate if it is less than 10 days from expiration.
> Check expiration date of ACME certificate

- cloudflare_worker/worker/src/index.ts
- tools/src/commands/gen_config/mod.rs
* In generated `wrangler.toml`, declare [Cron Triggers](https://developers.cloudflare.com/workers/platform/cron-triggers/) that runs every minute.
* Update OCSP and ACME state when receiving cron trigger event.
> Cron trigger

- sxg_rs/src/acme/state_machine.rs
Fix the bug that #282 did not update the test code.
> Fix wait time in tests to 59 seconds

- cloudflare_worker/README.md
- input.example.yaml
- sxg_rs/src/config.rs
- sxg_rs/src/lib.rs
- tools/src/commands/gen_config/mod.rs
* Set `html_host` field in `sxg_rs::Config` no longer optional.
* Remove unnecessary `domain_name` field in `tools::gen_config::Config`.
> Use single source of truth of worker html host

- cloudflare_worker/worker/src/index.ts
Fix that the promise was not awaited
> Fix a bug that ACME certificate was not added

- http_server/src/main.rs
Only attach sxg-rs-error in the wrapper function handle_or_error, instead of
the fn handle which is called by SelfFetcher. This makes the link
header-integrity match the subresource's header-integrity again. This was
broken by commit 2741af4f.
Addresses #250.
> Fix header-integrity for preloads.

- http_server/src/main.rs
> Process HTML if signing fails.

- fastly_compute/src/main.rs
Return `fastly::Error` rather than plain text messages, when an error is raised.
After we return, the outside Fastly runtime creates an HTTP 500 response with the message in `fastly::Error` struct.
> Use error type from Fastly crate

- distributor/example.html
- distributor/instantpage.js.patch
I think this is the better change to upstream.
> Change asDocument to a generic link modifier

- sxg_rs/src/lib.rs
> Add cache control to SXG outer header
